# Generated by Django 2.0.5 on 2018-05-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestureMetric',
            fields=[
                ('source', models.TextField(primary_key=True, serialize=False)),
                ('source_id', models.TextField()),
                ('attention_stat', models.IntegerField(default=100)),
                ('emotional_stat', models.TextField()),
                ('time_counter', models.IntegerField(default=1)),
                ('yawn_count', models.IntegerField(default=1)),
            ],
        ),
    ]
